-- MT5 OHLCV Data Collector - Database Schema
-- Includes ML features table for Zone-to-Zone strategy
-- Run this manually if you prefer direct SQL setup

-- ============================================================
-- 1. CORE OHLCV TABLE (unchanged)
-- ============================================================
CREATE TABLE IF NOT EXISTS ustech_ohlcv (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    hour INTEGER NOT NULL,
    day_of_week TEXT NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    open DECIMAL(18, 6) NOT NULL,
    high DECIMAL(18, 6) NOT NULL,
    low DECIMAL(18, 6) NOT NULL,
    close DECIMAL(18, 6) NOT NULL,
    volume DECIMAL(18, 6) NOT NULL,
    direction TEXT NOT NULL,
    candle_size DECIMAL(18, 6) NOT NULL,
    body_size DECIMAL(18, 6) NOT NULL,
    wick_upper DECIMAL(18, 6) NOT NULL,
    wick_lower DECIMAL(18, 6) NOT NULL,
    session TEXT NOT NULL DEFAULT 'unknown',
    CONSTRAINT unique_symbol_timeframe_timestamp
        UNIQUE (symbol, timeframe, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_timeframe_timestamp
ON ustech_ohlcv (timeframe, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_session
ON ustech_ohlcv (session);

CREATE INDEX IF NOT EXISTS idx_timeframe_session
ON ustech_ohlcv (timeframe, session);

-- ============================================================
-- 2. ML FEATURES TABLE
-- Stores engineered features + labels per bar.
-- Generated by ml_dataset.py — do not edit manually.
-- ============================================================
CREATE TABLE IF NOT EXISTS ustech_features (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL,

    -- Raw OHLCV (kept for reference)
    open DECIMAL(18, 6),
    high DECIMAL(18, 6),
    low DECIMAL(18, 6),
    close DECIMAL(18, 6),
    volume DECIMAL(18, 6),

    -- ---- Zone Features ----
    demand_zone_top DECIMAL(18, 6),
    demand_zone_bottom DECIMAL(18, 6),
    demand_zone_strength DECIMAL(8, 4),
    demand_zone_fresh INTEGER,
    demand_zone_touches INTEGER,

    supply_zone_top DECIMAL(18, 6),
    supply_zone_bottom DECIMAL(18, 6),
    supply_zone_strength DECIMAL(8, 4),
    supply_zone_fresh INTEGER,
    supply_zone_touches INTEGER,

    nearest_demand_dist_atr DECIMAL(10, 4),
    nearest_supply_dist_atr DECIMAL(10, 4),
    in_demand_zone INTEGER,
    in_supply_zone INTEGER,
    between_zones INTEGER,

    -- ---- Confirmation Signals ----
    bullish_engulfing INTEGER,
    bearish_engulfing INTEGER,
    pin_bar_bullish INTEGER,
    pin_bar_bearish INTEGER,
    higher_low INTEGER,
    lower_high INTEGER,
    bos_bullish INTEGER,
    bos_bearish INTEGER,
    buy_confirmation_score INTEGER,
    sell_confirmation_score INTEGER,

    -- ---- Technical Indicators ----
    atr_14 DECIMAL(18, 6),
    rsi_14 DECIMAL(8, 4),
    ema_20 DECIMAL(18, 6),
    ema_50 DECIMAL(18, 6),
    ema_200 DECIMAL(18, 6),
    ema_spread_atr DECIMAL(10, 4),
    price_above_ema20 INTEGER,
    price_above_ema50 INTEGER,
    price_above_ema200 INTEGER,
    ema_trend_bias INTEGER,
    bb_position DECIMAL(10, 4),
    bb_width_atr DECIMAL(10, 4),
    volume_ratio DECIMAL(10, 4),
    body_atr_ratio DECIMAL(10, 4),
    momentum_5 DECIMAL(10, 4),
    momentum_10 DECIMAL(10, 4),

    -- ---- HTF Context ----
    htf_1h_bias INTEGER,
    htf_4h_bias INTEGER,
    htf_aligned INTEGER,

    -- ---- Candle Context ----
    hour INTEGER,
    day_of_week TEXT,
    month INTEGER,
    session TEXT,
    direction TEXT,
    candle_size DECIMAL(18, 6),
    body_size DECIMAL(18, 6),
    wick_upper DECIMAL(18, 6),
    wick_lower DECIMAL(18, 6),

    -- ---- Labels (Zone-to-Zone strategy) ----
    signal INTEGER,             -- 1=buy, -1=sell, 0=no signal
    signal_reason TEXT,
    trade_outcome INTEGER,      -- 1=TP hit, -1=SL hit, 0=expired
    label INTEGER,              -- final ML label: 1, -1, or 0
    tp_price DECIMAL(18, 6),
    sl_price DECIMAL(18, 6),
    rr_ratio DECIMAL(8, 4),

    -- Prevent duplicate feature rows
    CONSTRAINT unique_features_symbol_tf_ts
        UNIQUE (symbol, timeframe, timestamp)
);

-- Indexes for fast ML queries
CREATE INDEX IF NOT EXISTS idx_features_timeframe_ts
ON ustech_features (timeframe, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_features_label
ON ustech_features (label);

CREATE INDEX IF NOT EXISTS idx_features_signal
ON ustech_features (signal);

CREATE INDEX IF NOT EXISTS idx_features_session
ON ustech_features (session);

-- ============================================================
-- 3. VIEWS
-- ============================================================

-- Main OHLCV view (unchanged)
CREATE OR REPLACE VIEW ustech_view AS
SELECT
    id, symbol, timeframe, timestamp, date, time, hour,
    day_of_week, month, year, open, high, low, close, volume,
    direction, candle_size, body_size, wick_upper, wick_lower, session
FROM ustech_ohlcv
ORDER BY
    CASE timeframe
        WHEN '1min'  THEN 1  WHEN '2min'  THEN 2  WHEN '3min'  THEN 3
        WHEN '4min'  THEN 4  WHEN '5min'  THEN 5  WHEN '10min' THEN 6
        WHEN '15min' THEN 7  WHEN '30min' THEN 8  WHEN '1H'    THEN 9
        WHEN '4H'    THEN 10 WHEN '1D'    THEN 11 ELSE 99
    END,
    timestamp DESC;

-- ML-ready view: only labeled signal rows
CREATE OR REPLACE VIEW ustech_signals AS
SELECT *
FROM ustech_features
WHERE signal != 0
ORDER BY timeframe, timestamp DESC;

-- Win rate summary by timeframe and session
CREATE OR REPLACE VIEW ustech_signal_stats AS
SELECT
    timeframe,
    session,
    COUNT(*) FILTER (WHERE signal != 0) AS total_signals,
    COUNT(*) FILTER (WHERE label = 1)   AS buy_winners,
    COUNT(*) FILTER (WHERE label = -1)  AS sell_winners,
    COUNT(*) FILTER (WHERE trade_outcome = -1 AND signal != 0) AS losers,
    ROUND(
        COUNT(*) FILTER (WHERE label != 0)::NUMERIC /
        NULLIF(COUNT(*) FILTER (WHERE signal != 0), 0) * 100, 2
    ) AS win_rate_pct,
    ROUND(AVG(rr_ratio) FILTER (WHERE signal != 0), 2) AS avg_rr
FROM ustech_features
GROUP BY timeframe, session
ORDER BY timeframe, win_rate_pct DESC;


-- ============================================================
-- Useful queries
-- ============================================================

-- Check signal win rate by timeframe:
-- SELECT * FROM ustech_signal_stats;

-- Get all buy signals on 5min:
-- SELECT timestamp, close, tp_price, sl_price, rr_ratio, trade_outcome
-- FROM ustech_signals WHERE timeframe = '5min' AND signal = 1;

-- Export ML features for training (Python: pd.read_sql):
-- SELECT * FROM ustech_features WHERE timeframe = '5min' AND label != 0;